### PR TITLE
Added new ES2015 processor for angular1.x

### PR DESCRIPTION
**Pull request by DominicBoettger**
Example: 

``` js
import angular from 'angular';

class alarmsPaneDirective {
  constructor($rootScope) {
    this.restrict = 'E';
    this.replace = true;
    this.templateUrl = 'alarmsPaneDirective.tpl.html';
    this.scope = {
      config: '=',
      data: '='
    };
    this.controller.$inject = ["$scope"];
  }
  controller($scope) {

  }
  static dfactory($rootScope) {
    return new alarmsPaneDirective($rootScope);
  }
}

let m = angular.module('alarmsPaneDirective', []);

alarmsPaneDirective.dfactory.$inject = ['$rootScope'];
m.directive('alarmsPane', alarmsPaneDirective.dfactory);

export default m;
```

### CODE REVIEW

**Comment by laxa1986** [comment]
Hello. I just released a version 2.1.3 with documentation fix. And will
release version 2.2.0 with major update in couple of hours. Your changes
can be released in version 2.3.0

2016-02-19 21:20 GMT+02:00 DominicBoettger <notifications@github.com>:

> Example:
>
> import angular from 'angular';
> class alarmsPaneDirective {
>   constructor($rootScope) {
>     this.restrict = 'E';
>     this.replace = true;
>     this.templateUrl = 'alarmsPaneDirective.tpl.html';
>     this.scope = {
>       config: '=',
>       data: '='
>     };
>     this.controller.$inject = ["$scope"];
>   }
>   controller($scope) {
>
>   }
>   static dfactory($rootScope) {
>     return new alarmsPaneDirective($rootScope);
>   }
> }
> let m = angular.module('alarmsPaneDirective', []);
> alarmsPaneDirective.dfactory.$inject = ['$rootScope'];m.directive('alarmsPane', alarmsPaneDirective.dfactory);
> export default m;
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/laxa1986/gulp-angular-embed-templates/pull/12
> Commit Summary
>
>    - Added Processor for ES2015 files
>    - Adde processor
>    - remove deletion of skipTemplates to be able to run multiple
>    processors.
>
> File Changes
>
>    - *M* CHANGELOG.md
>    <https://github.com/laxa1986/gulp-angular-embed-templates/pull/12/files#diff-0>
>    (6)
>    - *M* index.js
>    <https://github.com/laxa1986/gulp-angular-embed-templates/pull/12/files#diff-1>
>    (5)
>    - *A* lib/Angular1ES2015Processor.js
>    <https://github.com/laxa1986/gulp-angular-embed-templates/pull/12/files#diff-2>
>    (116)
>    - *M* lib/RegexpProcessor.js
>    <https://github.com/laxa1986/gulp-angular-embed-templates/pull/12/files#diff-3>
>    (4)
>    - *M* package.json
>    <https://github.com/laxa1986/gulp-angular-embed-templates/pull/12/files#diff-4>
>    (2)
>
> Patch Links:
>
>    -
>    https://github.com/laxa1986/gulp-angular-embed-templates/pull/12.patch
>    - https://github.com/laxa1986/gulp-angular-embed-templates/pull/12.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laxa1986/gulp-angular-embed-templates/pull/12>.
>



-- 
Чекулаев Алексей

**Comment by DominicBoettger** [comment]
Should i change anything?

**Comment by laxa1986** [comment]
Oh, no, you should not. I will apply your changes manually. Will it be
comfortable for you if I made it on weekend?

Only reason why I didn't apply then on previous weekend - I made major fix
and waited for some feedback on it, I didn't want to make two major updates
in one day.

2016-02-22 11:52 GMT+02:00 DominicBoettger <notifications@github.com>:

> Should i change anything?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laxa1986/gulp-angular-embed-templates/pull/12#issuecomment-187100646>
> .
>



-- 
Чекулаев Алексей

**Comment by DominicBoettger** [comment]
No, i am completely fine if you do the changes on the next weekend. Thanks for your feedback and your work!

**Pull request closed without merging**
